version: '3.8'

services:
  web:
    build: .
    ports:
      - "5050:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
